# Generated by Django 5.2.6 on 2025-09-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('home', 'Home Jersey'), ('away', 'Away Jersey'), ('third', 'Third Jersey')], default='home', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('club_name', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(blank=True, max_length=20)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('condition', models.CharField(default='Mint', max_length=50)),
                ('authenticity', models.BooleanField(default=True)),
            ],
        ),
    ]
