# Generated by Django 5.2.6 on 2025-09-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('second', 'Second'), ('mint', 'Mint')], default='Mint', max_length=50),
        ),
    ]
